/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ArkheBridgePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var crypto = __toESM(require("crypto"));
var ArkheBridgePlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.addCommand({
      id: "generate-note-hash",
      name: "Generate SHA-256 hash for current note",
      callback: () => this.generateHashForCurrentNote()
    });
    this.addCommand({
      id: "validate-seal",
      name: "Validate seal against hash",
      callback: () => this.validateSealCommand()
    });
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian.TFile && file.extension === "md") {
          this.updateHashInFrontmatter(file);
        }
      })
    );
    this.app.arkhe = {
      getNoteHash: (file) => this.getNoteHash(file),
      validateSeal: (file) => this.validateSeal(file)
    };
  }
  async generateHashForCurrentNote() {
    const file = this.app.workspace.getActiveFile();
    if (!file) {
      new import_obsidian.Notice("No active file");
      return;
    }
    const content = await this.app.vault.read(file);
    const hash = crypto.createHash("sha256").update(content).digest("hex");
    await this.app.fileManager.processFrontMatter(file, (fm) => {
      fm.hash = hash;
      fm.timestamp = (/* @__PURE__ */ new Date()).toISOString();
    });
    new import_obsidian.Notice(`Hash gerado: ${hash.slice(0, 8)}...`);
  }
  async updateHashInFrontmatter(file) {
    const content = await this.app.vault.read(file);
    const newHash = crypto.createHash("sha256").update(content).digest("hex");
    await this.app.fileManager.processFrontMatter(file, (fm) => {
      if (fm.hash !== newHash) {
        fm.hash = newHash;
        fm.modified = (/* @__PURE__ */ new Date()).toISOString();
      }
    });
  }
  getNoteHash(file) {
    var _a;
    const cache = this.app.metadataCache.getFileCache(file);
    return ((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.hash) || null;
  }
  validateSeal(file) {
    var _a, _b;
    const cache = this.app.metadataCache.getFileCache(file);
    const seal = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.selo;
    const hash = (_b = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _b.hash;
    if (!seal || !hash) return false;
    return seal.includes(hash.slice(0, 8));
  }
  validateSealCommand() {
    const file = this.app.workspace.getActiveFile();
    if (!file) {
      new import_obsidian.Notice("No active file");
      return;
    }
    const isValid = this.validateSeal(file);
    if (isValid) {
      new import_obsidian.Notice("Selo v\xE1lido!");
    } else {
      new import_obsidian.Notice("Selo inv\xE1lido ou ausente!");
    }
  }
};
